import {
  catalog,
} from "./catalog-data";
import type {
  BoardSpace,
} from "./types";

const locationCardsByName = new Map(catalog.cards.filter((card) => card.type === "location").map((card) => [card.name, card]));

const sixPlayerBoardSpaceArtById: Record<string, { imagePath: string; thumbnailPath: string; sourceSlug: string }> = {
  carthag: {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-carthag.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-carthag.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-carthag",
  },
  "controversial-tech": {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-controversial-technology.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-controversial-technology.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-controversial-technology",
  },
  "desert-mastery": {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-desert-mastery.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-desert-mastery.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-desert-mastery",
  },
  "economic-support": {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-economic-support.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-economic-support.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-economic-support",
  },
  expedition: {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-expedition.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-expedition.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-expedition",
  },
  "habbanya-erg": {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-habbanya-erg.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-habbanya-erg.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-habbanya-erg",
  },
  "hardy-warriors": {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-hardy-warriors.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-hardy-warriors.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-hardy-warriors",
  },
  "military-support": {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-military-support.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-military-support.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-military-support",
  },
  sardaukar: {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-sardaukar-6p.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-sardaukar-6p.webp",
    sourceSlug: "dire-wolf-design-diary-5-sardaukar-personal-board",
  },
  swordmaster: {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-swordmaster-6p.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-swordmaster-6p.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-swordmaster",
  },
  "vast-wealth": {
    imagePath: "/assets/dune-cards-hub/location/uprising-location-vast-wealth.webp",
    thumbnailPath: "/assets/dune-cards-hub/location/uprising-location-vast-wealth.webp",
    sourceSlug: "dire-wolf-six-player-board-space-guide-vast-wealth",
  },
};

function withBoardSpaceArt(space: BoardSpace): BoardSpace {
  const sixPlayerArt = sixPlayerBoardSpaceArtById[space.id];
  if (sixPlayerArt) return { ...space, ...sixPlayerArt };
  if (space.personal) return space;
  const card = locationCardsByName.get(space.name);
  if (!card) return space;
  return {
    ...space,
    imagePath: card.localImagePath ?? card.fullImageUrl ?? undefined,
    thumbnailPath: card.localThumbnailPath ?? card.thumbnailImageUrl ?? card.localImagePath ?? undefined,
    sourceId: card.id,
    sourceSlug: card.slug,
  };
}

const boardSpaceSpecs: BoardSpace[] = [
  {
    id: "dutiful-service",
    name: "Dutiful Service",
    zone: "Faction",
    icon: "emperor",
    influence: "emperor",
    contract: true,
    detail: "Emperor influence and a face-up CHOAM contract.",
  },
  {
    id: "economic-support",
    name: "Economic Support",
    zone: "Faction",
    icon: "emperor",
    influence: "greatHouses",
    gain: { spice: 1 },
    team: "trade",
    detail: "Great Houses influence, spice, then teammate trade.",
  },
  {
    id: "military-support",
    name: "Military Support",
    zone: "Faction",
    icon: "emperor",
    cost: { spice: 2 },
    influence: "greatHouses",
    troops: 3,
    team: "reinforce",
    detail: "Recruit three troops split across allied teammates.",
  },
  {
    id: "vast-wealth",
    name: "Vast Wealth",
    zone: "Faction",
    icon: "emperor",
    influence: "emperor",
    gain: { solari: 3 },
    team: "commander",
    personal: "shaddam",
    detail: "Commander-side Emperor pressure and Solari.",
  },
  {
    id: "sardaukar",
    name: "Sardaukar",
    zone: "Faction",
    icon: "emperor",
    cost: { spice: 3 },
    influence: "emperor",
    gain: { intrigue: 1 },
    troops: 4,
    team: "commander",
    personal: "shaddam",
    detail: "Shaddam personal-board space; 3 spice in six-player mode.",
  },
  {
    id: "hardy-warriors",
    name: "Hardy Warriors",
    zone: "Faction",
    icon: "fremen",
    cost: { water: 1 },
    influence: "fremen",
    troops: 2,
    combat: true,
    team: "commander",
    personal: "muaddib",
    detail: "Fremen influence and two recruited troops.",
  },
  {
    id: "expedition",
    name: "Expedition",
    zone: "Faction",
    icon: "fremen",
    influence: "fringeWorlds",
    contract: true,
    detail: "Fringe Worlds influence and a face-up CHOAM contract.",
  },
  {
    id: "controversial-tech",
    name: "Controversial Technology",
    zone: "Faction",
    icon: "fremen",
    cost: { spice: 2 },
    influence: "fringeWorlds",
    draw: 1,
    gain: { intrigue: 1 },
    detail: "Fringe Worlds influence, Intrigue, draw, and trash.",
  },
  {
    id: "desert-mastery",
    name: "Desert Mastery",
    zone: "Faction",
    icon: "fremen",
    influence: "fremen",
    gain: { spice: 1 },
    draw: 1,
    combat: true,
    team: "commander",
    personal: "muaddib",
    detail: "Fremen influence, card draw, spice, combat.",
  },
  {
    id: "sietch-tabr",
    name: "Sietch Tabr",
    zone: "City",
    icon: "city",
    requirement: { faction: "fringeWorlds", amount: 2 },
    combat: true,
    sietchTabr: true,
    detail: "Requires 2 Fremen/Fringe influence; choose Hooks, troop, water or water and remove the Shield Wall.",
  },
  {
    id: "arrakeen",
    name: "Arrakeen",
    zone: "City",
    icon: "city",
    troops: 1,
    draw: 1,
    combat: true,
    detail: "Recruit, draw, and city control income.",
  },
  {
    id: "carthag",
    name: "Carthag",
    zone: "City",
    icon: "city",
    gain: { intrigue: 1 },
    troops: 1,
    combat: true,
    detail: "Recruit a troop and take an Intrigue.",
  },
  {
    id: "research-station",
    name: "Research Station",
    zone: "City",
    icon: "city",
    cost: { water: 2 },
    troops: 2,
    draw: 2,
    combat: true,
    detail: "High-value draw and deployment point.",
  },
  {
    id: "swordmaster",
    name: "Swordmaster",
    zone: "Landsraad",
    icon: "landsraad",
    cost: { solari: 8 },
    detail: "Six-player single-use Swordmaster, then +2 reveal strength.",
  },
  {
    id: "high-council",
    name: "High Council",
    zone: "Landsraad",
    icon: "landsraad",
    cost: { solari: 5 },
    gain: { spice: 2, intrigue: 1 },
    troops: 3,
    detail: "Council seat or repeat reward shell.",
  },
  {
    id: "gather-support",
    name: "Gather Support",
    zone: "Landsraad",
    icon: "landsraad",
    troops: 2,
    detail: "Recruit two troops; optionally pay 2 Solari for 1 water.",
  },
  {
    id: "secrets",
    name: "Secrets",
    zone: "Faction",
    icon: "bene",
    influence: "bene",
    gain: { intrigue: 1 },
    detail: "Bene Gesserit influence and intrigue pressure.",
  },
  {
    id: "espionage",
    name: "Espionage",
    zone: "Faction",
    icon: "bene",
    cost: { spice: 1 },
    influence: "bene",
    draw: 1,
    spy: 1,
    detail: "Influence, draw, and place a spy.",
  },
  {
    id: "deliver-supplies",
    name: "Deliver Supplies",
    zone: "Faction",
    icon: "spacing",
    influence: "spacing",
    gain: { water: 1 },
    detail: "Spacing Guild influence and water.",
  },
  {
    id: "accept-contract",
    name: "Accept Contract",
    zone: "Spice Trade",
    icon: "spice",
    draw: 1,
    contract: true,
    detail: "Draw a card and take a face-up CHOAM contract.",
  },
  {
    id: "shipping",
    name: "Shipping",
    zone: "Spice Trade",
    icon: "spice",
    cost: { spice: 3 },
    requirement: { faction: "spacing", amount: 2 },
    gain: { solari: 5 },
    detail: "Requires 2 Spacing Guild Influence, then gains Solari and any one Influence.",
  },
  {
    id: "spice-refinery",
    name: "Spice Refinery",
    zone: "City",
    icon: "city",
    gain: { solari: 2 },
    combat: true,
    detail: "Gain 2 Solari, or pay 1 spice for 4 Solari, and contest city control.",
  },
  {
    id: "heighliner",
    name: "Heighliner",
    zone: "Faction",
    icon: "spacing",
    cost: { spice: 5 },
    influence: "spacing",
    troops: 5,
    combat: true,
    detail: "Guild influence and a heavy troop deployment.",
  },
  {
    id: "imperial-basin",
    name: "Imperial Basin",
    zone: "Desert",
    icon: "spice",
    gain: { spice: 1 },
    combat: true,
    maker: true,
    detail: "Maker space with bonus spice.",
  },
  {
    id: "habbanya-erg",
    name: "Habbanya Erg",
    zone: "Desert",
    icon: "spice",
    cost: { water: 1 },
    gain: { spice: 2 },
    draw: 1,
    combat: true,
    maker: true,
    detail: "Six-player Maker space with draw.",
  },
  {
    id: "hagga-basin",
    name: "Hagga Basin",
    zone: "Desert",
    icon: "spice",
    cost: { water: 1 },
    gain: { spice: 2 },
    combat: true,
    maker: true,
    makerWorms: 1,
    detail: "Maker space; choose 2 spice or a sandworm with Maker Hooks.",
  },
  {
    id: "deep-desert",
    name: "Deep Desert",
    zone: "Desert",
    icon: "spice",
    cost: { water: 3 },
    gain: { spice: 4 },
    combat: true,
    maker: true,
    makerWorms: 2,
    detail: "Deep maker space; choose 4 spice or two sandworms with Maker Hooks.",
  },
];

export const boardSpaces: BoardSpace[] = boardSpaceSpecs.map(withBoardSpaceArt);
